export declare class Diff {
    history: any[];
    currentStep: number;
    el: HTMLElement;
    diffData: any[];
    o: string;
    n: string;
    currentMode: string;
    currentJump: number;
    autoScroll: boolean;
    showControls: boolean;
    showLineControl: boolean;
    controls: any[];
    oldVersion: any;
    oldVersionHandler(d: any): void;
    newVersion: any;
    newVersionHandler(d: any): void;
    displayMode: string;
    handleDisplayMode(): void;
    mergeChange: (diffArray: any[], sb: string, done: boolean) => void;
    componentWillLoad(): void;
    componentDidLoad(): void;
    load(): void;
    refresh: () => void;
    setDiffData(): void;
    loadItem(target: any, versionType: string): boolean;
    mergeCodes: (diffArray: any, index: any, isIncoming: any) => void;
    onUpdate: () => void;
    undo: () => boolean;
    redo: () => boolean;
    jump: (next: boolean) => boolean;
    render(): any;
}
